# ──────────────────────────────────────────────────────────────────────────────
# Move exclude_pattern to top‐level so it applies globally
exclude: |
  (?x)^(
    .*/cdisort\.(c|h)|             # cdisort.c, cdisort.h
    .*/disort\.hpp|                # disort.hpp
    .*/COPYING|                    # COPYING
    .*/DISORT2\.doc|               # DISORT2.doc
    .*/HOWTO_cdisort|              # HOWTO_cdisort
    .*/Makefile_cdisort|           # Makefile_cdisort
    .*/README_cdisort|             # README_cdisort
    .*/locate\.(c|h)|              # locate.c, locate.h
    .*/print_test\.c|              # print_test.c
    .*/test_cdisort.*\.c|          # test_cdisort(_*).c
    .*/pydisort\.cpp|              # pydisort.cpp
    python/__init__\.py         # python/__init__.py
  )$
# ──────────────────────────────────────────────────────────────────────────────
repos:
  ## 1. Global check =========================================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        entry: trailing-whitespace-fixer
        language: python
        # ← no per-hook exclude needed: the global `exclude:` already covers these files

      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.26.3
    hooks:
      - id: check-github-workflows

  ## 2. Per language check ===================================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: requirements-txt-fixer
      - id: check-toml
      - id: check-shebang-scripts-are-executable

  ## C/C++ related -----------------------------------------------------------
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        name: Fix C, C++, Objective-C, Java
        entry: clang-format-hook
        types_or: [c, c++, c#, objective-c, java]
        language: python
        args: [--style=Google, -i, --no-diff]

      - id: cppcheck
        name: Find warnings/errors in C, C++, and Objective-C
        entry: cppcheck-hook
        types_or: [c++, c#, objective-c]
        language: python
        args: [--check-config]
        files: \.(cpp|cc|cxx|h|hpp|hxx)$

  ## Python related ----------------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-docstring-first
      - id: check-ast
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: ["--line-length", "79"]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports==1.12.0]
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.5.0
    hooks:
      - id: pycln

  ## 3. Lints ================================================================
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: cpplint
        name: Find lints in C/C++
        entry: cpplint-hook
        types_or: [c, c++, c#, objective-c, cuda]
        language: python
        args:
          [
            "--filter=-legal/copyright,-build/include_subdir,-runtime/references,-build/include_order,-runtime/casting,-whitespace/indent_namespace,-build/include_what_you_use,-readability/fn_size,-whitespace/braces,-whitespace/parens,-whitespace/blank_line",
          ]
        files: \.(cpp|cc|cxx|h|hpp|hxx)$
