name: Publish Python wheels to PyPI

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: "Version tag to distribute (e.g., v1.0.0)"
        required: true

jobs:
  build_linux_wheels:
    name: Build Linux wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build

      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install cibuildwheel==2.16.2

      - name: Set version
        run: |
          VERSION_TAG=${{ github.event.inputs.version_tag }}
          VERSION=${VERSION_TAG#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Linux wheels
        env:
          CIBW_BUILD: cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*
          CIBW_ARCHS: x86_64 aarch64
          CIBW_ENVIRONMENT: "SETUPTOOLS_SCM_PRETEND_VERSION=${{ env.VERSION }}"
          CIBW_BEFORE_BUILD: "pip install torch"
        run: |
          python -m cibuildwheel --platform linux --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: linux-wheels
          path: ./wheelhouse/*.whl

  build_macos_wheels:
    name: Build macOS wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-14-arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install system dependencies
        run: |
          brew install cmake ninja

      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install cibuildwheel==2.16.2

      - name: Set version
        run: |
          VERSION_TAG=${{ github.event.inputs.version_tag }}
          VERSION=${VERSION_TAG#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build macOS wheels
        env:
          CIBW_BUILD: cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*
          CIBW_ARCHS: ${{ matrix.os == 'macos-14-arm64' && 'arm64' || 'x86_64' }}
          CIBW_ENVIRONMENT: "SETUPTOOLS_SCM_PRETEND_VERSION=${{ env.VERSION }}"
          CIBW_BEFORE_BUILD: "pip install torch"
        run: |
          python -m cibuildwheel --platform macos --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: macos-wheels
          path: ./wheelhouse/*.whl

  upload_pypi:
    name: Upload wheels to PyPI
    needs: [build_linux_wheels, build_macos_wheels]
    runs-on: ubuntu-latest
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          name: linux-wheels
          path: dist

      - name: Download macOS wheels
        uses: actions/download-artifact@v4
        with:
          name: macos-wheels
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
