name: PyPI Release

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: "Release version tag"
        default: "latest"
      branch:
        description: "Source branch"
        default: "main"
      build_os:
        description: "Select OS to build wheels for"
        required: true
        default: "MacOS"
        type: choice
        options:
          - Both
          - MacOS
          - Ubuntu

env:
  BUILD_TYPE: Release

jobs:
  build-macos:
    name: Build macOS wheels
    runs-on: macos-latest
    if: ${{ inputs.build_os == 'Both' || inputs.build_os == 'MacOS' }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        include:
          - os: macos-latest
            target_arch: arm64
            cibw_arch: "arm64"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Determine version tag
        id: determine_version
        run: |
          echo "Input version tag: '${{ inputs.version_tag }}'"
          if [[ "${{ inputs.version_tag }}" == "latest" ]]; then
            git fetch --tags
            LATEST_TAG=$(git describe --tags --abbrev=0)
            echo "version=${LATEST_TAG}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ inputs.version_tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout tag if not 'latest'
        if: ${{ inputs.version_tag != 'latest' }}
        run: |
          echo "Checking out tag: ${{ steps.determine_version.outputs.version }}"
          git checkout ${{ steps.determine_version.outputs.version }}

      - name: Sanitize version
        run: |
          V="${{ steps.determine_version.outputs.version }}"
          echo "VERSION=${V#v}" >> $GITHUB_ENV

      - name: Configure wheel build env
        run: |
          PV=$(echo "${{ matrix.python-version }}" | tr -d '.')
          echo "PY_VERSION=$PV" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=11.1" >> $GITHUB_ENV
          echo "ARCHFLAGS=-arch ${{ matrix.target_arch }}" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install deps
        run: |
          grep -Ev '^(twine|sphinx|guzzle_sphinx_theme|pre-commit|clang-format|cppcheck|cpplint|pylint|sphinxcontrib-napoleon|ninja|setuptools|cmake)' requirements.txt > filtered.txt
          pip install -r filtered.txt

      - name: CMake configure
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DCMAKE_OSX_ARCHITECTURES=${{ matrix.target_arch }} \
            -DCMAKE_PREFIX_PATH="$(python -c 'import torch; print(torch.utils.cmake_prefix_path)')" \
            -DBUILD_TESTS=OFF

      - name: CMake build
        run: cmake --build build --parallel

      - name: Build macOS wheel
        env:
          CIBW_PLATFORM: macos
          CIBW_BUILD: cp${{ env.PY_VERSION }}*
          CIBW_ARCHS: ${{ matrix.cibw_arch }}
          CIBW_BEFORE_BUILD: |
            python -c "import re; open('filtered.txt','w').writelines([l for l in open('requirements.txt') if not re.match(r'^(twine|sphinx|guzzle_sphinx_theme|pre-commit|clang-format|cppcheck|cpplint|pylint|sphinxcontrib-napoleon|ninja|setuptools|cmake)', l)])" && \
            pip install -r filtered.txt && \
            cmake -B build -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
                  -DCMAKE_CXX_FLAGS_RELEASE="-Os -s" \
                  -DBUILD_TESTS=OFF && \
            cmake --build build --parallel
        run: |
          export TORCH_LIB=$(python -c 'import torch; print(torch.__path__[0] + "/lib")')
          export DYLD_FALLBACK_LIBRARY_PATH="$TORCH_LIB:$DYLD_FALLBACK_LIBRARY_PATH"
          pip install cibuildwheel
          python -m cibuildwheel --output-dir wheelhouse

      - name: Upload macOS wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-${{ matrix.python-version }}-${{ matrix.target_arch }}
          path: wheelhouse/*.whl

  build-linux:
    name: Build Ubuntu wheels
    runs-on: ubuntu-latest
    if: ${{ inputs.build_os == 'Both' || inputs.build_os == 'Ubuntu' }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        include:
          - os: ubuntu-latest
            target_arch: x86_64
            cibw_arch: "x86_64"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Determine version tag
        id: determine_version
        run: |
          echo "Input version tag: '${{ inputs.version_tag }}'"
          if [[ "${{ inputs.version_tag }}" == "latest" ]]; then
            git fetch --tags
            LATEST_TAG=$(git describe --tags --abbrev=0)
            echo "version=${LATEST_TAG}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ inputs.version_tag }}" >> $GITHUB_OUTPUT
          fi
      - name: Checkout tag if not 'latest'
        if: ${{ inputs.version_tag != 'latest' }}
        run: |
          echo "Checking out tag: ${{ steps.determine_version.outputs.version }}"
          git checkout ${{ steps.determine_version.outputs.version }}

      - name: Sanitize version
        run: |
          V="${{ steps.determine_version.outputs.version }}"
          echo "VERSION=${V#v}" >> $GITHUB_ENV

      - name: Configure wheel build env
        run: |
          PV=$(echo "${{ matrix.python-version }}" | tr -d '.')
          echo "PY_VERSION=$PV" >> $GITHUB_ENV

      - name: Build Ubuntu wheel
        env:
          CIBW_PLATFORM: linux
          CIBW_BUILD: cp${{ env.PY_VERSION }}*
          CIBW_ARCHS: ${{ matrix.cibw_arch }}
          CIBW_SKIP: "*musllinux*"
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: >
            PYTORCH_LIB=$(python -c "import torch; print(torch.__path__[0] + '/lib')") &&
            LD_LIBRARY_PATH=$PYTORCH_LIB auditwheel repair -w {dest_dir} {wheel}
          CIBW_BEFORE_BUILD: |
            pip install torch --extra-index-url https://download.pytorch.org/whl/cpu && \
            python -c "import re; open('filtered.txt','w').writelines([l for l in open('requirements.txt') if not re.match(r'^(twine|sphinx|guzzle_sphinx_theme|pre-commit|clang-format|cppcheck|cpplint|pylint|torch|sphinxcontrib-napoleon|ninja|setuptools|cmake)', l)])" && \
            pip install -r filtered.txt && \
            TORCH_LIB=$(python -c "import torch; print(torch.__path__[0] + '/lib')") && \
            TORCH_CMAKE_PREFIX_PATH=$(python -c "import torch.utils; print(torch.utils.cmake_prefix_path)") && \
            export LD_LIBRARY_PATH="$TORCH_LIB:$LD_LIBRARY_PATH" && \
            cmake -B build -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
                  -DCMAKE_CXX_FLAGS_RELEASE="-Os -s" \
                  -DPython3_EXECUTABLE=$(which python) \
                  -DCMAKE_PREFIX_PATH="$TORCH_CMAKE_PREFIX_PATH" \
                  -DBUILD_TESTS=OFF && \
            cmake --build build --parallel
        run: |
          pip install cibuildwheel
          python -m cibuildwheel --output-dir wheelhouse

      - name: Upload Ubuntu wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-ubuntu-${{ matrix.python-version }}-${{ matrix.target_arch }}
          path: wheelhouse/*.whl

  publish-pypi:
    name: Publish to PyPI
    if: ${{ always() }}
    needs: [build-macos, build-linux]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*

      - name: Merge wheels
        run: |
          mkdir dist
          find . -name '*.whl' -exec mv {} dist/ \;

      - name: Publish to PyPI
        if: ${{ needs.build-macos.result == 'success' || needs.build-ubuntu.result == 'success' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
